pipeline {
    agent any

    stages {
        stage('Pull') {
            steps {
                echo 'Pulling sccessful'
            }
        }
        stage('Build') {
            steps {
                sh '''
                cd backend
                mvn package -DskipTests
                '''
            }
        }
        stage('Test') {
            steps {
                withSonarQubeEnv('sonarqube') {  
                    sh '''
                    cd backend
                    mvn clean package -DskipTests sonar:sonar   -Dsonar.projectKey=studentapp   -Dsonar.projectName=\'studentapp\'
                    '''
       }
              }
        }
        stage('Quality-gate'){
            steps{
                timeout(10) {
    waitForQualityGate abortPipeline: true, credentialsId: 'sonar-cred'
            }
        }
        }
        stage('S3-UPLOAD')
        {
            steps{
                sh 'aws s3 cp target/student-registration-backend-0.0.1-SNAPSHOT.jar s3://amazon-demo-bucket-741/studentapp.jar '
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying done....'
            }
        }
    }
}